language: ruby
rvm:
  - 1.9.3
sudo: required
services:
  - xvfb
addons:
    chrome: stable
before_script:
  - "export PHANTOMJS_EXECUTABLE='phantomjs --ignore-ssl-errors=yes --local-to-remote-url-access=yes'"
